import type { Metadata } from "next";
import { Roboto } from "next/font/google";

import "./globals.css";
import { MainLayout } from "./_components/layouts";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const roboto = Roboto({
    subsets: ["latin"],
    weight: ["300", "400", "500", "700", "900"],
});

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
            <body className={roboto.className}>
                <MainLayout>{children}</MainLayout>
            </body>
        </html>
    );
}
